            - name: Gitleaks
  # You may pin to the exact commit or the version.
  # uses: gitleaks/gitleaks-action@e6dab246340401bf53eec993b8f05aebe80ac636
  uses: gitleaks/gitleaks-action@v2.3.4
          
